title: '&aDrop'
enable-all:
  - '&aEnable all'
  - LIME_WOOL
disable-all:
  - '&cDisable all'
  - RED_WOOL
auto-sell:
  - '&eAuto Sell'
  - SUNFLOWER
drop-to-inv:
  - '&eDrop to inventory'
  - CHEST
enabled: '&aEnabled'
disabled: '&cDisabled'
multi-items: true # several items fall out when digging stone
blocks: # from which blocks will drop items
  - stone
  - andesite
# Variables: %status, %chance, %min, %max, %exp, %money
itemlore:
  - '&7Status: %status'
  - '&7Chance: %chance'
  - '&7Money: %money'
custom-names: true
itemlist:
  -'1':
    item: iron_ingot
    chance: 50.0
    min: 1
    max: 50
    exp: 10
    money: 10
    name: '&3Iron :)'
  -'2':
    item: gold_ingot
    chance: 30.3
    min: 1
    max: 50
    exp: 10
    money: 20
    name: '&8Gold :('
  -'3':
    item: diamond
    chance: 5.7
    min: 1
    max: 50
    exp: 10
    money: 50
    name: '&eDiamond'
  -'4':
    item: iron_ingot
    chance: 40.0
    min: 1
    max: 50
    exp: 10
    money: 10
    name: '&3Iron :)'
